platform :ios, '12.0'
use_frameworks!

target 'craftyBlankState_Example' do
  pod 'craftyBlankState', :path => '../'

  target 'craftyBlankState_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
